---
name: Build white paper document
"on":
  push:
    branches: [master]
#     paths: ["white-paper/**"]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@2.2.0
        with:
          working_directory: ./white-paper
          root_file: wp.tex
      - name: Set env
        run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
      - name: Upload to Artipie as latest
        uses: "artipie/upload-action@v0.1"
        with:
          repo: "degit/wp"
          file: "./white-paper/wp.pdf"
          path: "white-paper-latest.pdf"
          username: "${{ secrets.ARTIPIE_USERNAME }}"
          password: "${{ secrets.ARTIPIE_PASSWORD }}"
      - name: Upload to Artipie with version
        uses: "artipie/upload-action@v0.1"
        with:
          repo: "degit/wp"
          file: "./white-paper/wp.pdf"
          path: "white-paper-${{ env.GITHUB_SHA_SHORT }}.pdf"
          username: "${{ secrets.ARTIPIE_USERNAME }}"
          password: "${{ secrets.ARTIPIE_PASSWORD }}"
